--- 
title: "Functional programming and unit testing for data munging"
author: "Bruno Rodrigues"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
    bookdown::gitbook
    bookdown::pdf_book
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This book is an introduction to functional programming and unit testing with the R programming language, for the purpose of data muning"
---

# Why this book?

This short book serves to show how functional programming and unit testing can be useful for the task
of data munging. This book is not an in-depth guide to functional programming, nor unit testing with R.
There are better resources to learn 
[functional progamming](http://adv-r.had.co.nz/Functional-programming.html) and 
[unit testing](http://r-pkgs.had.co.nz/tests.html) with R. But I will introduce the main ideas. I
will also show how to build your own R package that will hold all the code to clean your data and 
accompagnying documentation. Again, there are [great resources online](http://r-pkgs.had.co.nz/) 
to learn about packages. I will just cover the basics, and explain why having your code inside a 
packages makes sense when using functional programming and unit tests with R.

This book is not an introduction to R either. I will assume that you have intermediate knowledge of R.

## Motivation

Functional programming has very nice features that make working on data sets much more pleasant. It is 
common that you have to repeat the same instructions over and over again for different data sets that
look very similar (for example, same, or similar column names). Of course, it is possible to loop
over these data sets and repeat a set of instructions that change these data sets. However, we will see
why a functional programming approach is to be preferred. 

Unit testing then allows you to make sure that the functions you want to apply to your data sets actually
do what you really want them to do. Knowing and applying these two concepts together will make you 
hopefully a better data analyst. 

## Who am I?

I use R daily at my current job, and discovered R some years ago while I was at the 
[University of Strasbourg](http://www.unistra.fr/index.php?id=accueil). I'm not an R developer, and don't
have a CS background. Most, if not everything, that I know about R is self-taught. I hope however
that you will find this book useful. You can [follow me on twitter](https://twitter.com/brodriguesco)
or check [my blog](http://t.co/Hd94HCx0Wf).

## Thanks

I'd like to thank [Ross Ihaka](https://www.stat.auckland.ac.nz/~ihaka/) and [Robert Gentleman](https://en.wikipedia.org/wiki/Robert_Gentleman_(statistician)) for developing the R 
programming language. Many thanks to [Hadley Wickham](http://hadley.nz/) for all the wonderful
packages he developed that make R much more pleasant to use. Thanks to [Yihui Yie](http://yihui.name/)
for `bookdown` without which this book would not exist (at least not in this very nice format). 

Thanks to [Hans-Martin von Gaudecker](https://www.iame.uni-bonn.de/people/hm-gaudecker) for 
introducing me to unit testing and writing elegant code. The PEP 8 style guidelines will forever 
remain etched in my brain.

Finally I have to thank my wife for putting up with my endless rants against people not using 
functional programming nor testing their code (or worse, using proprietary software!). 
